<h1>OnePages Overview</h1>
<section id="creations">
    <?php
    //foreach ($this->onepage as $page) {

//               var_dump($page);
        echo "<article id='page'>";
        echo "<h1>" . $this->page['title'] . "</h1>";
        echo "<div id='description'>";
        echo "<p>" . $this->page['description'] . "</p>";
        echo "</div>";

        echo '</article>';
    //};
    ?>
</section >