<html>
    <head>
        <title>Test layout1</title>
        <link href="/public/css/style.css" rel="stylesheet" />
         <meta charset="UTF-8" />
        <!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
  </head>
    <body>
        <div id="container">
            <header>
                <div id="logo">
                    <img src="/public/images/logo.png" alt="Tweet" width="200" />
                </div>
                <nav>
                                        <!--
                    <?php
                        echo $this->navigation()->menu(); ?>-->
                    <ul>
                        <li><a href="/public/page/">Refresh</a></li>
                      </ul> 
                </nav>
            </header>
            <section id="content">
                <?php echo $this->layout()->content; ?>
            </section>
        </div>
    </body>
</html>
